### ISSUE TITLE
Compilation error with fresh build depending on didkit 0.3.0

### ISSUE THREAD

**Issue by cobward** [spruceid/didkit#277]
Building a crate that depends on didkit 0.3.0 will fail for fresh builds (no Cargo.lock). This can be replicated by creating a new crate which only depends on didkit 0.3.0 and running `cargo build`.

This is due to didkit 0.3.0 depending on ssi 0.3.0 and did_methods of the form "x.y". Did method crates increment `z` when ssi is upgraded, so both ssi v0.4.0 and v0.3.0 are in the dependency tree of didkit.

I suggest:
- We release didkit v0.3.1 and yank v0.3.0.
- Going forwards in didkit we always depend on did method versions of the form `x.y.z` to prevent ssi version clashes.

**Comment by clehner** [comment]
I think this is fixed; @cobward can you confirm?

**Comment by cobward** [comment]
Yes, just checked. This works now by depending on 0.3.1. Do we want to yank 0.3.0?

**Comment by nayrban** [comment]
I also saw that for ssi version 0.3 the ethr version is 0.0.1 not 0.1.0 so we still have the compile issue
